-- Enable realtime
ALTER DATABASE postgres SET "suppress_repetitive_errors" = off;
ALTER DATABASE postgres SET "wal_level" = logical;

-- Disable RLS for demo purposes
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_methods DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
